apiVersion: v2
name: pn-kargo
description: Kargo is a progressive continuous delivery platform
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
- kargo
- continuous-delivery
- progressive-delivery
- progressive-delivery-controller

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: 'ci/cd'
  platform.pnats.cloud/component: kargo
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'kargo'
  platform.pnats.cloud/resource-type: controller
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: kargo
  platform.pnats.cloud/component-category: 'ci/cd'

dependencies:
- name: kargo
  version: 1.8.3
  repository: oci://ghcr.io/akuity/kargo-charts
