---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: temporal-postgres-secret
  namespace: temporal
spec:
  encryptedData:
    password: AgC5aSnH7+4BdDbPomwpc7mmlRyIyA/O4Xibit8sWBPTRGVvtiIAIxx58DsNy/MvTS8OqhGD9hHVmRcLVMliYw53csUVLsOLjH7lbOyHqYCDZsn70xRAIqA4j1ZHmJ76CGk1F3xl5zp+AheeDsbUWrUsGMN0+iqPs4hb2BV8zOMhVLzh0CDpf1dzmIfH350lJmRcQ2TzQSqs1BvwPfLMRchSEYTAsK+XvcFgGUjFc5WKFeu8/JCFxfUjw0N6rOws7q5rpeMzIulK0O75lEeIS1xmmtTgS6Ksz2OQNthAW5enbJJf485bF+/oTyl9CK7Q+y7RrRFinMfLluHrG9ImVP/eqFG8pnzUb4TIShOIFB4cdiojIgsCV/fbRFwHTSsr0ANys/Tni2uIj5wN3gKIhrwqJ2Wla7VptyJAPH3SMl87mB1srLHgPziF2hl3c6opOPgDRL0lbTNpbTDsY0tiBpUrXUmJbW/25pfUEe7qc1MqNo6kRogFb8RPM33v5xDxwbmvvqivYqCbjw6cxq+8RiAGc2dAdYRzNVH1EBavySDRXp/Wp3O/7Y+APZqIGKiXQBoaZg6IL5kQZLC8pxWjMh5GBN18jd4lyTQmIPXyBmBrxq1o/Qlb1mud7FTqQmDrz0E2xxcLpSUdZUTZIlQW5U1N1+gtO5gwzM7l1372IPlAU/ZGyMmS98+i3YS9glJotU2r5GL9hQysTsulXYnynDDtMTuT2H4SrCiQaSyhKaNnlrG1H7ruF+0RyopNg0dIo6tZomdJaZr2yG7j+WCwMJ2d
    postgres-password: AgBRuE/qKfWRYQuU2NiDmEPqqA5wrscaT+FIct5dG0HRH8/KdVxb5BaaK+ryD5YbGblfPilGuzrPRyvfE2xlttF2Km98bHqmxYHRG4hcNB8CFMmkDVgmCQ7v/Wwhz3v2xDbHFd9yp8mKm/Jm1zkgejg82Tm8y6Dv6fZQaUf0pKbUIDHpqk2mRqOB1PS6nz53Hu6RRzRSPSoZg+5/tGiKgD6JToC4/46RRM9gk6ZFuZUS1G0f3qKZ6/AajC2XLsmRzsH/bkm+0FQYev1mcFXYSSfQvOgwvK5lLKXETJrI551MaQwCExaF2PEpsOJa2GQMQwbUQRvjIRmr0Acwevx8Rl5FK4isSy5g8qaNapI62sdBoHN/SiytnHQMio1zZv64h75KrnJeQTuzFCbqTM7ACv7RWZXjsUs1t5OzP+VSIwtYtNdSO275V6y+ke/KPyXqXorMsCXjAYHOJpzb+TBjKJ9cKU3c+7v3Jux9NtWDU1HNhh6aMu4SinO154UGxM2wB2BBp8rk4BksG/A1up9OM53zR1YpCsVmetkohxuh5k1TkYp5B6eup2P4M7IR9ZaaW105go7uDl8w3u5B04IcuSNuAZrTurspCmgt1RaKCouf+ItMoNa3aAN1itiR2wnyXJcjfUBkcmzT2Ih/ge7l2/YLWt0syJ5JOizyrAs9mrOTn8WbUsVU/LVuTHYTyfhhdzYsQ4XY3hYuFgCkU83XSJ2I2E+PemT3h0mpISRPYpJNjBSbfoOEUkBePcmFxlsvErqwCPRN/4viO6XrtoQ60hJ1
  template:
    metadata:
      name: temporal-postgres-secret
      namespace: temporal
    type: Opaque
