apiVersion: v2
name: argo-rollouts
description: Argo Rollouts for progressive delivery controller for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
- argo-rollouts
- continuous-delivery
- progressive-delivery
- progressive-delivery-controller

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: 'ci/cd'
  platform.pnats.cloud/component: argo-rollouts
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'argo-rollouts'
  platform.pnats.cloud/resource-type: controller
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: argo-rollouts
  platform.pnats.cloud/component-category: 'ci/cd'

dependencies:
- name: argo-rollouts
  version: 2.40.5
  repository: https://argoproj.github.io/argo-helm
