apiVersion: v2
name: pn-prometheus
description: Prometheus monitoring stack for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
- prometheus
- metrics-database
- timeseries-database
- metrics-storage
- monitoring

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: monitoring
  platform.pnats.cloud/component: prometheus
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'prometheus'
  platform.pnats.cloud/resource-type: application
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: prometheus
  platform.pnats.cloud/component-category: monitoring

dependencies:
- name: kube-prometheus-stack
  version: 65.1.1
  repository: https://prometheus-community.github.io/helm-charts
