## Kafbat Kafka-UI Configuration
## Values passed to upstream kafka-ui chart

kafka-ui:
  replicaCount: 1

  image:
    registry: ghcr.io
    repository: kafbat/kafka-ui
    pullPolicy: IfNotPresent
    tag: ""

  ## Kafbat-UI config in Yaml format
  yamlApplicationConfig:
    kafka:
      clusters:
        - name: pn-kafka
          bootstrapServers: pn-kafka-kafka-bootstrap.strimzi-kafka-operator.svc:9092
    auth:
      type: disabled

  ## Resource allocation
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  ## Service configuration
  service:
    type: ClusterIP
    port: 80

  ## Ingress configuration
  ingress:
    enabled: false
    ingressClassName: nginx
    host: kafka-ui.example.com
    path: "/"
    pathType: Prefix
    annotations: {}
    tls:
      enabled: false
      secretName: ""

  ## Probes configuration
  probes:
    useHttpsScheme: false
    liveness:
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 10
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 10

  ## Network Policy
  networkPolicy:
    enabled: false

  ## Node selector
  nodeSelector: {}

  ## Tolerations
  tolerations: []

  ## Affinity
  affinity: {}
