# Platform applications with sync wave ordering
applications:
- name: temporal
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  sources:
  - repoURL: https://github.com/ProficientnowTech/pn-infra.git
    targetRevision: v2
    path: platform/stacks/application-infra/charts/temporal
  - repoURL: https://github.com/ProficientnowTech/pn-infra.git
    targetRevision: v2
    path: platform/stacks/application-infra/charts/temporal/secrets
  - repoURL: https://github.com/ProficientnowTech/pn-infra.git
    targetRevision: v2
    path: platform/stacks/application-infra/charts/temporal/dashboards
