apiVersion: v2
name: pn-external-secrets
description: Kubernetes Operator to sync secrets from external secret management systems
namespace: external-secrets
type: application
version: 1.0.0
appVersion: "0.11.0"

keywords:
- secret-management
- secrets-sync
- vault-integration
- security
- external-secrets-operator

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: secret-management
  platform.pnats.cloud/component: secrets-operator
  platform.pnats.cloud/docs: 'https://external-secrets.io'
  platform.pnats.cloud/deploys: 'external-secrets-operator'
  platform.pnats.cloud/dependencies: '[{"name":"vault","type":"secret-backend"}]'

labels:
  platform.pnats.cloud/component: secrets-operator
  platform.pnats.cloud/component-category: 'security/secret-management'

dependencies:
- name: external-secrets
  alias: external-secrets
  version: 1.1.0
  repository: https://charts.external-secrets.io
