apiVersion: v1
kind: Service
metadata:
  name: fuma-docs
spec:
  selector:
    app: fuma-docs
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
