# Tekton Operator Configuration
global:
  namespace: tekton
  project: development-workloads

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/ttl: "60"
  className: nginx
  tls:
    enabled: true
  host: tekton.pnats.cloud

operator:
  name: tekton-operator-app
  source:
    repo: https://storage.googleapis.com/tekton-releases
    targetRevision: latest
    path: operator/latest
  namespace: tekton-operator
