apiVersion: v2
name: pn-metallb
description: Metallb with Public IP Pool and L2 Advertisements
type: application
version: 0.1.0
appVersion: "0.15.2"

keywords:
- metallb
- public-ip-pool
- external-ip-address

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

dependencies:
- name: metallb
  version: 0.15.2
  repository: https://metallb.github.io/metallb
