apiVersion: v2
name: scylladb-operator
description: ScyllaDB Operator for managing ScyllaDB clusters on Kubernetes
type: application
version: 0.1.0
appVersion: "1.19.0"

keywords:
- scylladb
- database
- nosql
- cassandra
- wide-column-store

annotations:
  category: Database
  platform.pn-infra.io/component: scylladb-operator
  platform.pn-infra.io/sync-wave: "150"

dependencies:
- name: scylla-operator
  version: v1.19.0
  repository: https://scylla-operator-charts.storage.googleapis.com/stable
