apiVersion: v2
name: pn-kafka-cluster
description: Baseline Strimzi Kafka cluster (ZooKeeper mode) for PN Infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - kafka
  - strimzi
  - data-streaming

maintainers:
  - name: Platform Team
    email: platform-team@pnats.cloud
