argocdNamespace: argocd
stackName: backup-and-disaster-recovery
default:
  repoURL: https://github.com/pnow-devsupreme/pn-infra.git
  targetRevision: v2
global:
  project: backup-dr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  retry:
    limit: 3
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
commonLabels:
  platform.pnats.cloud/stack: backup-dr
  platform.pnats.cloud/layer: operations
  app.kubernetes.io/managed-by: platform-core
commonAnnotations:
  platform.pnats.cloud/managed-by: platform-core
  platform.pnats.cloud/generated-by: platform-core-chart
applications: []
dependencies: []
dependencyCheck:
  enabled: true
  pollIntervalSeconds: 10
  image: docker.io/library/busybox:1.36.1
