apiVersion: v2
name: pn-debezium
description: Debezium Change Data Capture for ProficientNow Cloud Platform
type: application
version: 1.0.0
appVersion: "3.3.1"

keywords:
- change-data-capture
- cdc
- debezium

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: data-streaming
  platform.pnats.cloud/component: debezium
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'debezium'
  platform.pnats.cloud/resource-type: CRDs
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: debezium
  platform.pnats.cloud/component-category: data-streaming

dependencies:
- name: debezium-operator
  version: 3.3.1
  repository: https://charts.debezium.io
