apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.flowCollector.namespace }}
  labels:
    app.kubernetes.io/name: netobserv
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    platform.pnats.cloud/component: netobserv
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
