{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: netobserv-operator-metrics
  namespace: {{ .Values.flowCollector.namespace }}
  labels:
    app.kubernetes.io/name: netobserv-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: netobserv-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: ClusterIP
  selector:
    control-plane: netobserv-operator
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
{{- end }}
