{{- if .Values.operator.enabled }}
{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Values.flowCollector.namespace }}
  labels:
    app.kubernetes.io/name: netobserv-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
{{- end }}
