{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netobserv-operator
  namespace: {{ .Values.flowCollector.namespace }}
  labels:
    app.kubernetes.io/name: netobserv-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  selector:
    matchLabels:
      control-plane: netobserv-operator
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
