---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: public-l2-announcement
spec:
  loadBalancerIPs: true
  interfaces:
    - public_traffic
  nodeSelector:
    matchLabels: {}  # Apply to all nodes
