apiVersion: v2
name: pn-ceph-cluster
description: Ceph Cluster for ProficientNow Cloud Distributed Storage
type: application
version: 1.0.0
appVersion: "v1.18.7"

keywords:
- storage
- storage-cluster
- ceph
- distributed-storage
- ceph-cluster
- rook-ceph-cluster
- k8s-storage

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: storage
  platform.pnats.cloud/component: rook-ceph-cluster
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'rook-ceph-cluster'
  platform.pnats.cloud/resource-type: 'RookCephCluster'
  platform.pnats.cloud/dependencies: '["ingress-nginx","cert-manager","external-dns","metallb"]'

labels: []

dependencies:
- name: rook-ceph-cluster
  version: 1.18.7
  repository: https://charts.rook.io/release
