apiVersion: v2
name: rook-ceph-cluster
description: Wrapper chart for Rook Ceph cluster plus platform-specific resources
type: application
version: 0.2.0
appVersion: "v18.2.4"

keywords:
  - storage
  - ceph
  - rook
  - distributed-storage

annotations:
  category: Storage
  platform.pn-infra.io/component: rook-ceph-cluster

dependencies:
  - name: rook-ceph-cluster
    version: v1.18.4
    repository: https://charts.rook.io/release
