apiVersion: v2
name: pn-kafka-operator
description: Strimzi Kafka Operator for PN Infrastructure
type: application
version: 0.1.0
appVersion: "0.48.0"

keywords:
- data-streaming
- kafka

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: data-streaming
  platform.pnats.cloud/component: kafka
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'kafka'
  platform.pnats.cloud/resource-type: Operator
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: kafka
  platform.pnats.cloud/component-category: data-streaming

dependencies:
- name: strimzi-kafka-operator
  version: 0.48.0
  repository: https://strimzi.io/charts/
