applications:
- name: pg-clusters
  project: platform-data
  sources:
  - repoURL: https://github.com/ProficientnowTech/pn-infra.git
    targetRevision: v2
    path: platform/stacks/platform-data/pg-clusters
  destinationNamespaceOverwrite: 'platform-pg-clusters'
  syncOptions:
  - ServerSideApply=true
  - CreateNamespace=true
  - RespectIgnoreDifferences=true
