apiVersion: v2
name: pn-crossplane
description: "Crossplane lets you build control planes to manage your cloud native software"
type: application
version: 1.0.0
appVersion: "v2.2.0"

keywords:
- control-plane
- api
- platform-api
- operator

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: platform-engineering
  platform.pnats.cloud/component: platfrom-control-plane
  platform.pnats.cloud/docs: ''
  platform.pnats.cloud/deploys: 'crossplane'
  platform.pnats.cloud/resource-type: CRDs
  platform.pnats.cloud/dependencies: '[]'

labels:
  platform.pnats.cloud/component: platfrom-control-plane
  platform.pnats.cloud/component-category: control-plane-framework

dependencies:
- name: crossplane
  version: 2.1.3
  repository: https://charts.crossplane.io/stable
