apiVersion: v2
name: pn-harbor-registry
description: Harbor for container image registry
type: application
version: 1.0.0
appVersion: "2.14.0"

dependencies:
- name: harbor
  version: 1.18.0
  repository: https://helm.goharbor.io
