apiVersion: v2
name: pn-vault
description: Hashicorp Vault for secure secrets management
namespace: vault
type: application
version: 1.0.0
appVersion: "v1.20.4"

keywords:
- secret-management
- vault
- hashicorp
- encryption
- secrets-storage
- pki
- security

maintainers:
- name: Platform Team
  email: snoorullah@proficientnowtech.com

annotations:
  platform.pnats.cloud/category: secret-management
  platform.pnats.cloud/component: secrets-backend
  platform.pnats.cloud/docs: 'https://developer.hashicorp.com/vault/docs'
  platform.pnats.cloud/deploys: 'hashicorp-vault'
  platform.pnats.cloud/dependencies: '["ingress-nginx","cert-manager","external-dns","metallb","external-secrets"]'

labels:
  platform.pnats.cloud/component: secrets-backend
  platform.pnats.cloud/component-category: 'security/secret-management'

dependencies:
- name: vault
  version: 0.30.1
  repository: https://helm.releases.hashicorp.com
