apiVersion: v1
kind: ServiceAccount
metadata:
  name: kroxylicious-operator
  namespace: {{ .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kroxylicious-operator-watched
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
rules:
  - apiGroups: ["kroxylicious.io"]
    resources:
      - kafkaproxies
      - virtualkafkaclusters
      - kafkaservices
      - kafkaproxyingresses
      - kafkaprotocolfilters
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["kafka.strimzi.io"]
    resources: ["kafkas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kroxylicious.io"]
    resources:
      - kafkaproxies/status
      - virtualkafkaclusters/status
      - kafkaservices/status
      - kafkaproxyingresses/status
      - kafkaprotocolfilters/status
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kroxylicious-operator-dependent
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
rules:
  - apiGroups: [""]
    resources:
      - services
      - serviceaccounts
      - configmaps
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kroxylicious-operator-watched
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kroxylicious-operator-watched
subjects:
  - kind: ServiceAccount
    name: kroxylicious-operator
    namespace: {{ .Values.namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kroxylicious-operator-dependent
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kroxylicious-operator-dependent
subjects:
  - kind: ServiceAccount
    name: kroxylicious-operator
    namespace: {{ .Values.namespace | quote }}

