---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-storage-public
  namespace: kube-system
  annotations:
    description: "Ceph public network - Client traffic (VLAN 101)"
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net-storage-public.kube-system.ovn"
    }
