{{- if .Values.bootstrapSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-private-repo
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.bootstrapSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.bootstrapSecrets.secretStoreRef.name }}
    kind: {{ .Values.bootstrapSecrets.secretStoreRef.kind }}
  target:
    name: argocd-private-repo
    creationPolicy: Merge
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: name
      remoteRef:
        key: applications/infrastructure/argocd/repo
        property: name
    - secretKey: type
      remoteRef:
        key: applications/infrastructure/argocd/repo
        property: type
    - secretKey: url
      remoteRef:
        key: applications/infrastructure/argocd/repo
        property: url
    - secretKey: sshPrivateKey
      remoteRef:
        key: applications/infrastructure/argocd/repo
        property: sshPrivateKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.bootstrapSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.bootstrapSecrets.secretStoreRef.name }}
    kind: {{ .Values.bootstrapSecrets.secretStoreRef.kind }}
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
    - secretKey: slack-token
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: slack-token
    - secretKey: email-username
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: email-username
    - secretKey: email-password
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: email-password
    - secretKey: email-host
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: email-host
    - secretKey: email-port
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: email-port
    - secretKey: email-from
      remoteRef:
        key: applications/infrastructure/argocd/notifications
        property: email-from
{{- end }}
