argocdNamespace: argocd
stackName: data-streaming
default:
  repoURL: https://github.com/ProficientnowTech/pn-infra.git
  targetRevision: v2
global:
  project: data-streaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  retry:
    limit: 3
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
commonLabels:
  platform.pnats.cloud/stack: data-streaming
  platform.pnats.cloud/layer: data
  app.kubernetes.io/managed-by: platform-core
commonAnnotations:
  platform.pnats.cloud/managed-by: platform-core
  platform.pnats.cloud/generated-by: platform-core-chart
applications: []
